name: Android CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Clone repo
      uses: actions/checkout@v2

    - name: Replace API keys
      env:
        GMAP_API_DEBUG: ${{ secrets.GMAP_API_DEBUG }}
        GMAP_API_RELEASE: ${{ secrets.GMAP_API_RELEASE }}
      run: |
           sed --in-place \
             's/GOOGLE_MAPS_API_DEBUG/'"$GMAP_API_DEBUG"'/' \
             app/src/debug/res/values/google_maps_api.xml
           sed --in-place \
             's/GOOGLE_MAPS_API_RELEASE/'"$GMAP_API_RELEASE"'/' \
             app/src/release/res/values/google_maps_api.xml

    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8

    - name: Build with Gradle
      run: ./gradlew build --quiet
      continue-on-error: true

    - name: Upload Lint Report
      uses: actions/upload-artifact@v2
      with:
        name: LintReport
        path: app/build/reports/lint-results.html

    - name: Upload APK
      uses: actions/upload-artifact@v2
      with:
        name: ShareDocks_Debug
        path: app/build/outputs/apk/debug/app-debug.apk

